### ISSUE TITLE
traverse not stack safe

### ISSUE THREAD

**Issue by syaiful6** [sanctuary-js/sanctuary-type-classes#18]
title say it all, small repro:

https://jsfiddle.net/syaiful6/reh4dwnd/

**Comment by davidchambers** [comment]
Is it specifically [`Array$prototype$traverse`][1] that's problematic, do you think? If so, are you interested in working on an implementation which does not blow the stack? I'm not sure that it's possible, but it's definitely worth investigating. :)


[1]: https://github.com/sanctuary-js/sanctuary-type-classes/blob/v1.2.0/index.js#L646-L653

**Comment by syaiful6** [comment]
yes, it is. it's happen because large ```ap``` operation on there. I have an implementation that doesn't blow the stack. I will pull a PR when i have time.

**Comment by syaiful6** [comment]
okay i already open a PR, ready to review.
