### ISSUE TITLE
Z.toString cannot handle NodeJS Buffer

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary-type-classes#31]
EDIT: I originally thought it was worse, I thought `Buffer#toString` throws an error when not given its encoding argument. Turns out the default behavior just returns a string of Unicode identifiers.

```
> Z.toString({x: new Buffer([1,2,3])})
'{"x": \u0001\u0002\u0003}'
```

Should we special-case this? Maybe provide an override `toString` function for Buffer somehow?

EDIT: I would say "no" now that I've realized that it's not throwing an error.

**Comment by davidchambers** [comment]
I don't know how buffers should be handled. Is `equals(eval(toString(x)), x) = true` feasible for `x :: Buffer`?

> Maybe provide an override `toString` function for Buffer somehow?

If we decide to define `Buffer#toString` there's a very clear way to go about having `Z.toString` use the implementation:

1.  Define `Buffer$prototype$toString :: Buffer ~> () -> String`.

2.  Add this to `implementations`:

    ```javascript
    Buffer: {
      prototype: {
        toString: Buffer$prototype$toString
      }
    }
    ```

We're living the OO dream. :)

**Comment by Avaq** [comment]
> Is `equals(eval(toString(x)), x) = true` feasible for `x :: Buffer`?

Buffers are just byte-arrays. They can be represented and constructed in a number of different ways. One such ways is providing an `Array UInt8` (eg; `[0, ..., 255]`) to its constructor: `new Buffer([...])`. We could therefore say that:

```js
Buffer$prototype$toString = function(){
  return 'new Buffer(' + toString(Array.from(this)) + ')';
};
```

Or show a more concise base64 representation like this:

```js
Buffer$prototype$toString = function(){
  return 'new Buffer(' + toString(this.toString('base64')) + ', "base64")';
};
```

---

All of this brings me to another thought: How is Sanctuary handling the new native JavaScript types, `Map`, `WeakMap`, typed int arrays, `Promise`? If we were to special-case `Buffer` to meet `equals(eval(toString(x)), x) = true`, I suppose we would then have to do the same for all of these other types. I'm not sure if we would want to do this. Honestly the reason I opened this issue is because I feared that `Buffer#toString` was throwing an exception (falsely confirmed by running `Z.toString(new Buffer)`, what was actually happening is `Buffer()` throwing an exception). I'm not sure if we want to special-case any types for a non-breaking reason.

**Comment by Avaq** [comment]
I'm closing this issue based on my own preferences, and @davidchambers recent Gitter message:

> I'd like Sanctuary to remain focused on the parts of the JavaScript language I consider good. It's for this reason that I'm not excited by the possibility of supporting native maps and sets in Z.toString. The right solution is to provide our own Map and Set types (with value-based equality semantics) which won't require special treatment.
