### ISSUE TITLE
Add Object#ap and Object#of

### ISSUE THREAD

**Issue by gabejohnson** [sanctuary-js/sanctuary-type-classes#34]
In the Gitter room David demonstrated that `ap` can be implemented for `Object`. `of` is trivial.

```js
// ap :: StrMap (a -> b) -> StrMap a -> StrMap b
Z.ap({}, {})
// {}
Z.ap({x: S.words, y: S.words}, {})
// {}
Z.ap({}, {x: 'foo bar', y: 'baz'})
// {}
Z.ap({x: S.words, y: S.words}, {x: 'foo bar'})
// {x: ['foo', 'bar']}
Z.ap({x: S.words, y: S.words}, {x: 'foo bar', y: 'baz'})
// {x: ['foo', 'bar'], y: ['baz']}

// of :: Object a -> StrMap a
Z.of(Object, {a: 1})
// {a : 1}
Z.of(Object, 1)
// {}
```
@davidchambers do I have this right?

**Comment by davidchambers** [comment]
> `of` is trivial.

Yes and no. ;)

    of :: Applicative f => TypeRep f -⁠> a -⁠> f a

Let's try replacing `Applicative f` with `StrMap`:

    StrMap$of :: a -⁠> StrMap a

The function above must return a value of type `StrMap a` given a value of type `a`. There are no constraints on `a`. As we discussed on Gitter, there are an infinite number of valid implementations, but they all feel arbitrary to me:

```javascript
//    StrMap$of :: a -> StrMap a
const StrMap$of = x => {'': x};
```

```javascript
//    StrMap$of :: a -> StrMap a
const StrMap$of = x => {foo: x};
```

```javascript
//    StrMap$of :: a -> StrMap a
const StrMap$of = x => {'rather-long-property-name': x};
```

Although we *could* implement `fantasy-land/of` for Object, I don't think we should.

I do think we should implement `fantasy-land/ap` for Object, though!

**Comment by kedashoe** [comment]
> Although we could implement fantasy-land/of for Object, I don't think we should.
> 
> I do think we should implement fantasy-land/ap for Object, though!

Makes sense. This makes we wonder though.. `filter` for objects is I think pretty straightforward, but we can't get there with our current derivations as object is not an applicative or monad. Is there an algebra for `append`? `Applicative` seems too restrictive to me.. we need `of` as we use `concat`, but all we really need is `append`, right?

**Comment by gabejohnson** [comment]
> As we discussed on Gitter, there are an infinite number of valid implementations, but they all feel arbitrary to me

Fair point. I was only considering `ownProperties`. If `Object.keys` returns an empty array I would treat it as an empty StrMap.

**Comment by davidchambers** [comment]
`of` can't make decisions based on the `a` value provided. Let's consider `{x: 1}` as the `a` value:

```javascript
{x: 1} :: StrMap Number, { x :: Number }
StrMap$of :: a -> StrMap a
StrMap$of({x: 1}) :: StrMap (StrMap Number), StrMap { x :: Number }
```

So, `StrMap$of({x: 1})` *cannot* give us `{x: 1}`. It must give us something like `{foo: {x: 1}}`.

> ```javascript
> Z.of(Object, 1)
> // {}
> ```

This adheres to the type signature, but a requirement not captured in the type signature is that the provided value must actually appear in the resulting value. ;)

**Comment by gabejohnson** [comment]
I concede. `ap` it is!

**Comment by davidchambers** [comment]
> `ap` it is!

Sounds good! Submit a pull request, if you would like to do so. :)

**Comment by gabejohnson** [comment]
@kedashoe what would `append` look like for `Object`?`Pair String a -> StrMap a -> StrMap a`?

**Comment by kedashoe** [comment]
> @kedashoe what would append look like for Object?Pair String a -> StrMap a -> StrMap a?

gah, you're right, it wouldn't work :disappointed:

**Comment by gabejohnson** [comment]
@kedashoe I've had need over the last couple of days for something like the above though. There are a few from [Haskell](https://hackage.haskell.org/package/TernaryTrees-0.2.0.2/docs/Data-Map-StringMap.html) that I wouldn't mind having around.

**Comment by kedashoe** [comment]
> @kedashoe I've had need over the last couple of days for something like the above though. There are a few from Haskell that I wouldn't mind having around.

Agreed, some useful stuff in there :) but would not work for what I had mentioned above
