### ISSUE TITLE
Add support for Keyed Collections

### ISSUE THREAD

**Issue by gabejohnson** [sanctuary-js/sanctuary-type-classes#39]
sanctuary-type-classes should support `Set`, `Map`, and to a lesser extent, `WeakSet` and `WeakMap`.

- [ ] `empty` -      `Set`, `Map`, `WeakSet`, `WeakMap`
- [ ] `of` -             `Set`, ~`Map`~, `WeakSet`, ~`WeakMap`~
- [ ] `zero` -         `Set`, `Map`, `WeakSet`, `WeakMap`
- [ ] `equals` -     `Set`, `Map`
- [ ] `toString` -   `Set`, `Map`
- [ ] `concat` -     `Set`, `Map`
- [ ] `map` -          `Set`, `Map`
- [ ] `ap` -             `Set`, `Map`
- [ ] `alt` -             `Set`, `Map`
- [ ] `reduce` -      `Set`, `Map`
- [ ] `chainRec` -  `Set`
- [ ] `chain` -        `Set`
- [ ] `traverse` -    `Set`
- [ ] `extend` -      `Set`

**Comment by safareli** [comment]
How would you define `of` for `Map`?
Also we should discuss functority of `Set`.

https://www.schoolofhaskell.com/user/chad/snippets/random-code-snippets/set-is-not-a-functor
https://gist.github.com/tpolecat/7401433
https://www.reddit.com/r/haskell/comments/2090x3/ask_rhaskell_why_is_there_no_functor_instance_for/

http://stackoverflow.com/a/19193815/1798418

**Comment by safareli** [comment]
related:
https://github.com/sanctuary-js/sanctuary-set
https://github.com/sanctuary-js/sanctuary-map

**Comment by gabejohnson** [comment]
@safareli I was motivated to own this issue by [this](https://gitter.im/sanctuary-js/sanctuary?at=58c2da12872fc8ce62e430a7) Gitter discussion. Does a JS `Set` have the `Ord` restriction?

**Comment by gabejohnson** [comment]
> How would you define of for Map?

`of = a => new Map([[a, a]])`

This is essentially a `Set` with a single entry.

**Comment by davidchambers** [comment]
I don't think `of = a => new Map([[a, a]])` is valid. The general type of `of` is:

> ```haskell
> of :: Applicative f => a -> f a
> ```

Let's replace `Applicative f => f` with `Map String`, say. The type is now:

```haskell
of :: a -> Map String a
```

What's the result of applying this to `42`? We need a value of type `Map String Number` but your function would produce a value of type `Map Number Number`. So really for `Map String` we have a function of type `String -> Map String String`.

**Comment by gabejohnson** [comment]
Of course you're right. This goes back to our conversation about `StrMap`.

**Comment by gabejohnson** [comment]
I'm not sure if the signature, but something like
`of :: a -> (b -> Map a b)`
I don't know the notation for fixing `a` to an instance.

**Comment by gabejohnson** [comment]
So `Map.of(42) // a -> Map 42 a`. I don't immediately see the utility though.

**Comment by safareli** [comment]
in purescript and haskell this is possible:
```haskell
instance applicativeMap :: (Monoid f) => Applicative (Map a) where
  pure a = singleton empty a
```
but in js it's not quite easy:/

**Comment by gabejohnson** [comment]
I removed `Map` and `WeakMap` from the Applicative entry. Are there any others I should remove?

**Comment by davidchambers** [comment]
I'm reluctant to encourage the use of these built-in types. I'd rather spend effort releasing [sanctuary-set][1] and [sanctuary-map][2], and updating Sanctuary functions such as [`keys`][3] to use these FL-compliant data types.


[1]: https://github.com/sanctuary-js/sanctuary-set
[2]: https://github.com/sanctuary-js/sanctuary-map
[3]: https://sanctuary.js.org/#keys

**Comment by gabejohnson** [comment]
Makes sense. There should be an easy way to convert between native and sanctuary types though. I'll close this add issues to the relevant repos.

**Comment by davidchambers** [comment]
> I'll close this add issues to the relevant repos.

Excellent! Thank you. :)
