### ISSUE TITLE
fantasy-land@3.2.0

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary-type-classes#43]
https://github.com/fantasyland/fantasy-land/compare/v3.1.0...v3.2.0

I believe that @gabejohnson is already working on this change. Could you confirm this, Gabe?

**Comment by gabejohnson** [comment]
That is correct. I have already implemented `Ord` for `Null`, `Undefined`, `Boolean`, `Number`, `Date`, and `String`. I plan to add `Array` and `Arguments` this weekend (they are assumed to have the same semantics).

**Comment by safareli** [comment]
I'm a bit lost, what's difference between #46 and #45

**Comment by davidchambers** [comment]
> I'm a bit lost, what's difference between #46 and #45

These pull requests were submitted independently, and the patches are largely duplicative (although #45 contains additions unrelated to fantasy-land@3.2.0 which could become separate pull requests).

I decided to keep both pull requests open as there were significant differences between them initially. They are gradually converging. At some point we'll close one and put our combined energy behind the other.
