### ISSUE TITLE
Derive flip from map

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary-type-classes#63]
```js
const flip = (f, x) => map(T(x), f)

flip(a => b => a - b, 1)(5) //> 4
flip({a: x => x - 1, b: x => x + 1}, 1) //> {a: 0, b: 2}
```

See https://hackage.haskell.org/package/functors-0.1/docs/Data-Functor-Syntax.html#v:flip

**Comment by Avaq** [comment]
Downside of this will be that function flip will become binary in Sanctuary

**Comment by gabejohnson** [comment]
PureScript calls it `flap`. Less confusing IMO.

**Comment by davidchambers** [comment]
> Downside of this will be that function flip will become binary in Sanctuary

A similar thing happened to `S.compose` in sanctuary-js/sanctuary#396. Losing the ability to write `S.flip(S.concat, '!')` would be a shame, and would increase our reliance on the placeholder.

> PureScript calls it `flap`. Less confusing IMO.

Perhaps we should include `Z.flap` here, and both `S.flip` and `S.flap` in Sanctuary. Thoughts?

**Comment by Avaq** [comment]
> Losing the ability to write `S.flip(S.concat, '!')` would be a shame

I don't think we'll lose that ability, actually. Just the ternary (fully applied) version.

**Comment by davidchambers** [comment]
If `S.flip(S.concat, '!')` will still work, I see only two reasons to keep `S.flip` in its current form:

  - the type signature is much clearer; and
  - `S.flip_` will seem out of place if `S.flip` becomes polymorphic.

I lean towards generalizing `S.flip` and removing `S.flip_`.

**Comment by Avaq** [comment]
It may still be worth considering `flap`, because it could be weird that `flip` is general, but `flip_` is specific to function. :man_shrugging: 

But I think I'd also be happy with general `flip` and ditching `flip_` or renaming it to `flipFunction` or something.

**Comment by gabejohnson** [comment]
What about
```js
flip :: ((a, b) -⁠> c) -⁠> b -⁠> a -⁠> c
flap :: Functor f => f (a -> b) -> a -> f b
```
?

**Comment by davidchambers** [comment]
Something about having `S.flip` operate on an uncurried function doesn't sit well with me, Gabe.

In fact, now that we have `S.curry2` and `S.curry3` I think we should consider removing `S.encase2_` and similar `_`-suffixed functions.

**Comment by davidchambers** [comment]
> I think we should consider removing `S.encase2_` and similar `_`-suffixed functions.

sanctuary-js/sanctuary#416

**Comment by Avaq** [comment]
I believe all of this will fall into place once simple currying lands.
