### ISSUE TITLE
Add `reduceMap` (aka `foldMap`)

### ISSUE THREAD

**Issue by gabejohnson** [sanctuary-js/sanctuary-type-classes#74]
@masaeedu was asking about implementing Haskell's `foldMap :: Monoid m => (a -> m) -> t a -> m`

In Haskell it's a class member of `Foldable` (as well as an alternate minimal definition).

I think `reduceMap :: (Foldable t, Monoid m) => TypeRep m -> (a -> m) -> t a -> m` would be an excellent addition to this project.

**Comment by masaeedu** [comment]
@gabejohnson Do you think just PR-ing the implementation you posted in Gitter would work? Just ran into a few more scenarios where I need this.

**Comment by gabejohnson** [comment]
Keep in mind the correction from @syaiful6. It should be a right fold (which we currently don't have in Sanctuary).

**Comment by masaeedu** [comment]
In terms of `reduce` (`foldl`), which is available, I believe it's:

```js
const foldMap = tr => f => S.reduce(b => a => S.concat(b)(f(a)))(S.empty(tr));

foldMap(String)(x => x.toString())([1, 2, 3])
// "123"
```
